### ISSUE TITLE
How to get the key be used in build.gradle

### ISSUE THREAD

**Issue by AbdElrahman-Rafaat-Amer** [Commencis/secrets-vault-plugin#10]
I am using poEditor and want to secure this keys using the lib.

Here is my build.gradle

plugins{
//plugins here
}
poEditor {
    apiToken.set("apitoken")
    projectId.set("projectid") //Note the projectid is int
    defaultLang.set("en")
}

android{
//....
}
dependencies{
//dependencies here
}

**Comment by burakaygun** [comment]
Hi @AbdElrahman-Rafaat-Amer,

The purpose of **Secrets Vault** is to store keys inside the final application (APK) securely. Build scripts (`build.gradle` files) are not included directly inside the final APK, but the code produced by them are. Hence, actually it should be fine not to secure keys **used only on build/compile time** unless you share your project's source code publicly.

If you still need to secure keys that is only used on build/compile time, you can store them as environment variables.

Note that if the keys are not used only on build/compile time, i.e., they are included inside the final APK, you should set them on **runtime** via Secrets Vault instead of build/compile time:

So, instead of doing:
```
someSDK {
  apiKey = "..."
}
```

You should do:
```
class MyApplication : Application() {
  override fun onCreate() {
    SomeSDK.setApiKey(MainSecrets().getSomeSDKApiKey())
  }
}
```
