### ISSUE TITLE
getYOURAPIKEY() not resolve calling from java

### ISSUE THREAD

**Issue by sonvirgo** [Commencis/secrets-vault-plugin#7]
In Kotlin everything works as expected, but from Java all method name are a0, a1, a2 ,...
Have to guess the name based on its order in secrets.json

**Comment by noman-bk** [comment]
Is there any update on it?

**Comment by sonvirgo** [comment]
Also the Plugin not work on debug mode.
All key are empty?
Why, already turn off app signature check.
So annoying.

**Comment by burakaygun** [comment]
Hi @sonvirgo,

Thank you for your feedback.

We've added a section to README about accessing the generated secret keys inside a `Java` class. You can check it [here](https://github.com/Commencis/secrets-vault-plugin?tab=readme-ov-file#access-inside-java).

About "plugin not working on debug mode":

We do not expect any problems related to debug mode. We've added a [sample app](https://github.com/Commencis/secrets-vault-plugin/tree/main/sampleapp) to the repo which has `debug` & `release` types. You can check it out, it works fine on both types. Please make sure that you run `keepSecrets` Gradle task after you update any plugin-related files in your project, such as `secrets.json` and `secretsVault { ... }` block in `build.gradle[.kts]`.

(Also, note that `keepSecrets` task may generate an incorrect `CMakeLists.txt` file which cannot be compiled. This should be fixed in `0.1.2` release of the plugin.)

If your problem with debug mode continues, please open a separate issue with more detail to spesific to that problem.

**Comment by sonvirgo** [comment]
> Hi @sonvirgo,
> 
> Thank you for your feedback.
> 
> We've added a section to README about accessing the generated secret keys inside a `Java` class. You can check it [here](https://github.com/Commencis/secrets-vault-plugin?tab=readme-ov-file#access-inside-java).
> 
> About "plugin not working on debug mode":
> 
> We do not expect any problems related to debug mode. We've added a [sample app](https://github.com/Commencis/secrets-vault-plugin/tree/main/sampleapp) to the repo which has `debug` & `release` types. You can check it out, it works fine on both types. Please make sure that you run `keepSecrets` Gradle task after you update any plugin-related files in your project, such as `secrets.json` and `secretsVault { ... }` block in `build.gradle[.kts]`.
> 
> (Also, note that `keepSecrets` task may generate an incorrect `CMakeLists.txt` file which cannot be compiled. This should be fixed in `0.1.2` release of the plugin.)
> 
> If your problem with debug mode continues, please open a separate issue with more detail specific to that problem.

Thank you for your value source code. It make secret string harder to retrieve for the attacker. But there is still some confuse in  signature fingerprint. I think it not like tamper protection right. Unfortunately, attacker send me a clip how he crack and mod my app. I think they tamper the app and your signature check is misleading. I have to now using NDK to read SHA256 signature at runtime to protect against tampering.

**Comment by sonvirgo** [comment]
> Hi [@sonvirgo](https://github.com/sonvirgo),
> 
> Thank you for your feedback.
> 
> We've added a section to README about accessing the generated secret keys inside a `Java` class. You can check it [here](https://github.com/Commencis/secrets-vault-plugin?tab=readme-ov-file#access-inside-java).
> 
> About "plugin not working on debug mode":
> 
> We do not expect any problems related to debug mode. We've added a [sample app](https://github.com/Commencis/secrets-vault-plugin/tree/main/sampleapp) to the repo which has `debug` & `release` types. You can check it out, it works fine on both types. Please make sure that you run `keepSecrets` Gradle task after you update any plugin-related files in your project, such as `secrets.json` and `secretsVault { ... }` block in `build.gradle[.kts]`.
> 
> (Also, note that `keepSecrets` task may generate an incorrect `CMakeLists.txt` file which cannot be compiled. This should be fixed in `0.1.2` release of the plugin.)
> 
> If your problem with debug mode continues, please open a separate issue with more detail specific to that problem.

Ah my mistake, debug mode change debug key signature every time new Android Studio and SDK installed an android.debugkey to ~/
